# https://taskfile.dev

version: "3"

tasks:
    default:
        # If no task is specified, we use the magic variable `TASK_EXE` to call `task` again with `--list`.
        # See https://github.com/go-task/task/issues/1562.
        silent: true
        cmds:
            - "{{.TASK_EXE}} --list"

    check-linting:
        desc: Run linting and apply fixes automatically
        cmd: uv run ruff check --fix
        sources:
            - src/**/*.py
            - exclude: src/**/_version.py
            - exclude: ./**/__pycache__/**/*

    check-types:
        desc: Run type checking
        cmd: uv run pyright
        sources:
            - src/**/*.py
            - exclude: src/**/_version.py
            - exclude: ./**/__pycache__/**/*

    check-format:
        desc: Apply standardised formatting fixes
        cmd: uv run ruff format
        sources:
            - src/**/*.py
            - exclude: src/**/_version.py
            - exclude: ./**/__pycache__/**/*

    check:
        desc: Run all checks
        cmds:
            - task: check-linting
            - task: check-types
            - task: check-format
    
    build:
        desc: Build Docker container image
        cmd: docker build . -t archedbrows:main 
    
    dev:
        desc: Run a development server
        cmd: uv run flask --app archedbrows run --debug {{.CLI_ARGS}}
    
    db:
        desc: Operate on database migrations (use `--` to pass further arguments)
        cmd: uv run flask --app archedbrows db {{.CLI_ARGS}}