"""Distinguish date added and date created

Revision ID: e334241b3252
Revises: 970413d7fe82
Create Date: 2025-02-21 15:20:49.747130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.functions import now

# revision identifiers, used by Alembic.
revision: str = "e334241b3252"
down_revision: str | None = "970413d7fe82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("time", new_column_name="time_created")
        batch_op.add_column(
            sa.Column("time_added", sa.DateTime(), nullable=False, server_default=now())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("time_created", new_column_name="time", nullable=True)
        batch_op.drop_column("time_added")

    # ### end Alembic commands ###
