"""Add thumbnails.

Revision ID: 32ec4859da01
Revises: e334241b3252
Create Date: 2025-03-05 23:07:29.257171

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32ec4859da01"
down_revision: str | None = "e334241b3252"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("thumb", sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_column("thumb")

    # ### end Alembic commands ###
